# Basic plotting example using ggplot2
# Generated by ChatGPT after the previous script, following the prompt:
#  "That's not right. I want a continuous color scale. In R the colors are categorical instead of continuous."

library(ggplot2)

n <- 1000  # Choose how many points to use
x <- rnorm(n)  # Create x coordinates
y <- rnorm(n)  # Create y coordinates
c <- sqrt(x^2 + y^2)  # Set color as distance from center

data <- data.frame(x = x, y = y, c = c)

ggplot(data, aes(x, y, color = c)) +
  geom_point(alpha = 0.5) +
  scale_color_continuous()